

export default function getRoute(start, end) {
    const token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6Ino0bGltZHk1ZzMiLCJ0b2tlbiI6eyJpdiI6IjhjNjM0NGFmZjc4NDIyODdhZGZkYjcxOWUzMzdkYWE2IiwiY29udGVudCI6IjhmYWU1N2I5MDNkMDdmNjZiNzE5MDIzNDcwMjkxYjhlYzZlMTQ3MTcxYTdhNmUyNDc3ZmViMjU2OWMwMTgwZDJiYTQ0Y2M4ZjgyOWQ4N2ZlM2U3ZmVlMmQ3ZmU3OTcxZTA3OGVjYzQ5NTA4MWUxODA0YzA1YzA5MTgzMmQzMGQxMTVkZDBiMDQ2ZGFhYjY0N2M4NWMxNzg2ODEzZjM3ZGZiYzg4YzUxMDJjMjk2ZGJkYzY4YzQ0MWE1NzI2M2YyNWQ1NWQ1OWVjZmUyMmFmMTIzZTFmZGZlMDRjNGRjMWYxNjcyZDJmYTRlZTY4ZWNkMWU1NGMyNjdlNjNkMGFiNjZmNjRjZGZlZmZiMzQwZGZmNmMyYWJjYmJjZDQ3MzRmMDFkNWU1Y2FkMGFiYWViOTkxZWFhNTY0NTQwYmU1MmI0ZmQzMjM3ZmI0MWU0ZWI1ZGJlMWNkZTkwNzk1MjlhNmE3MTJjZTk2Y2YxN2JlY2U4ZmEwNTNjNWM0NGFhNzY1NmQ2ZGRmYjU5YjRlYWFkMDVlMTJjYzBlMTc2YjMzNTYwYmEwZjE2YTU4YmNhMDM2OWExMDYxNTFjYzdjYTJlOGYzOWU3ZThkYzRiMTZmYTBjNjUxNjI4ZGRmYzg1ODFjODMzNDY3MTYxZTk1NTg3MzhhOTM1ZGY4ZWQwYzU1YzE2OTM3ZjdiNzY2YzhkMzJmMGY4N2RjM2VlMDM2NDA3OTUwNDcwMDM2ZDE1YjU0OTE5YjUyNmI1YTc3ZjVjMDk3NjI0NWEwNjJmZDc0MTA5ZDA3MjQ1ZTAzMzEzMjcxNThkNDM5YzRiNjY2MWNlNzZmZjczZDNjYWU0YjAyY2Q3MjBkNjQzMWNlNDNjOTc2ZGE1ZTM4NzM1In0sInNlY3VyaXR5VG9rZW4iOnsiaXYiOiI4YzYzNDRhZmY3ODQyMjg3YWRmZGI3MTllMzM3ZGFhNiIsImNvbnRlbnQiOiJhZmE0NzBhNjBmZTQyNTYzY2UyODc5NGM2ZTNiNjNmMWQyYmIzODBhM2E3YjdmNjc1N2ZhOGEyOTkzMjk5MmQ4ZDg2NWY3ZjJjMmIyOGRkZjYwMjhjZDEzIn0sImp0aSI6ImVkYTQ1M2M3LWRjNjctNDkzOS1hZjYxLTAyZTRjZDZhMjlmYSIsImlhdCI6MTY2ODI4OTY4NSwiZXhwIjoxNjY4MjkzMjg0fQ.3izaXeVonTA8pQmqtXQ_AiR6uotnc__ITs_c7_RDNkU";
    const url = `https://api.iq.inrix.com/findRoute?wp_1=${start}&wp_2=${end}&format=json&accessToken=${token}`;
  
    const data = {
        method : 'GET',
        headers: {
            'Content-Type': 'application/json'
        },
    };
    
    fetch(url, data).then(res => res.json()).then(data => console.log(data))
  }
  